version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=symfony
      - MARIADB_DATABASE=symfony
    ports:
      - '3306:3306'
  symfony:
    image: docker.io/bitnami/symfony:6.3
    ports:
      - '8000:8000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=symfony
      - SYMFONY_DATABASE_NAME=symfony
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton
    volumes:
      - './app:/app'
    depends_on:
      - mariadb
